# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa77814074e06e4f8c0a94aab12deb68726c5dbbcdbdba23ac332eba753e48ed02979433956e31f00b4d4648824722fc6b13faf92d745216f9d3c5f60b45e78

test:
  secret_key_base: dfe010546cc70ffbf28560c0450a72fe4ae15d7dcd897664603728c8ac320b2cce110ab4a6bd51550ada91b356a6208c2d5505cf13144a8f38394e278e97ea8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
